version: '3.0'

services:

  GOB_TEMPLATE_DOCKER_NAME:
    build: src
    container_name: GOB_TEMPLATE_DOCKER_NAME
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001

networks:
  default:
    external:
      name: gob-network
